/* Automatic generated by './build/bin/build-entry.js' */

import Grid from './components/grid/index';
import Icon from './components/icon/index';

const emui = {
  Col: Grid.Col,
  emCol: Grid.Col,
  Row: Grid.Row,
  emRow: Grid.Row,
  Icon,
};

//, opts = {}
const install = (Vue) => {
  if (install.installed) return;

  Object.keys(emui).forEach((key) => {
    Vue.component(key, emui[key]);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
};
